#!/bin/bash
## ========================================================
## Usage: 
##      run-dgeRibo-contrasts CONTRASTS CONFIG DIRLOC 
##
## Options:
##      CONTRASTS The contrasts, tab separated file with 2 columns, the condition to test on the first column,
##      and the reference on the second column, with a header on first line.
##      CONFIG The yaml config file to pass to the R script
##      DIRLOC The output directory to pass to the R script
##
## Description: 
##      Run run-dgeRibo-from-htseq.R for all contrasts in CONTRASTS
##
## Note:
##      The R script must be on the path or in the same directory

USAGE="CONTRASTS CONFIG DIRLOC "
: ${1?"Usage: $0 ${USAGE}"}
: ${2?"Usage: $0 ${USAGE}"}
: ${3?"Usage: $0 ${USAGE}"}

CONTRASTS="$1"
CONFIG="$2"
DIRLOC="$3"

while IFS=$'\t' read -r num denom
 do
  ./run-dgeRibo-from-htseq.R $CONFIG $num $denom $DIRLOC
 done < <(tail -n+2 "$1") 
