#!/bin/bash
## ========================================================
## Usage: 
##      create_trackDb PATH PARENT SHORTLABEL <LONGLABEL> <DICTMAPPING>
##
## Options:
##      LONGLABEL the longLabel description, default to the shortLabel
##      DICTMAPPING A description for the tracks, added to the longLabel
##      in the form key: value, one per line where key must match 
##      the "pretty_name" in the file names. Requires the LONGLABEL.
##
## Description: 
##      create the trackDb.txt file 

USAGE="PATH PARENT SHORTLABEL <LONGLABEL> <DICTMAPPING>"
: ${1?"Usage: $0 ${USAGE}"}
: ${2?"Usage: $0 ${USAGE}"}
: ${3?"Usage: $0 ${USAGE}"}

DIRLOC="$1"
PARENT="$2"
SHORTLABEL="$3"
LONGLABEL="${4:-$SHORTLABEL}"

declare -A NAME_DICT
if [ "$#" -eq 5 ]; then
 USED=1
 while IFS=":" read -r key value
 do
  NAME_DICT[$key]=$value
 done < "$5"
fi

# use defaults, see "create-bigBed-tracks" 
# adjust below if required
note=".orfs"

trackDb="trackDb.txt"
ftype="bigBed 12 + ."
itemRgb="on"
spectrum="on"
searchIndex="name"
html="off"

cat > ${trackDb} << EOF
track ${PARENT}
superTrack on
shortLabel ${SHORTLABEL}
longLabel ${LONGLABEL}

EOF

for f in ${DIRLOC}/*.bb; do 
 base=$(basename $f)
 name=${base%${note}*}
 echo "track ${name}"
 echo "parent ${PARENT}"
 echo "bigDataUrl ${base}"
 echo "shortLabel ${name}"
 if [ -z "$USED" ]; then
  echo "longLabel ${NAME_DICT[$name]}, ${LONGLABEL}"
 else
  echo "longLabel ${name}, ${LONGLABEL}"
 fi
 echo "type ${ftype}"
 if  [ ${html} == "on" ]; then
  echo "html ${filen}"
 fi        
 if  [ ${itemRgb} == "on" ]; then
  echo "itemRgb on"
 fi
 if  [ ${spectrum} == "on" ]; then
  echo "spectrum on"
 fi
 if  [ ${searchIndex} == "name" ]; then
  echo "searchIndex name"
 fi
 echo ""
done >> ${trackDb}
